import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import Footer from "./ui/landingpage/footer";
import Header from "./ui/customers/header";
import Nav from "./ui/landingpage/nav";

export const metadata = {
  title: "Primeunilum",
  description: "Generated by Primeunilum",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <div>
            {/* <div className="h-24 bg-gray-200"><Nav /></div> */}
            <div>
              {children}
            </div>
          </div>
          <Footer />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
