import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import Footer from "./ui/landingpage/footer";

export const metadata = {
  title: "Primeunilum",
  description: "Generated by Primeunilum",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          {children}
          <div>
            <Footer />
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
